### ISSUE TITLE
Modal not working on step 4.

### ISSUE THREAD

**Issue by MauriMatamoros** [VulcanJS/Vulcan-Starter#120] opened 2019-03-08 01:33 UTC
Nothing displays or changes plus there is an error log in the console.
![screen shot 2019-03-07 at 7 33 19 pm](https://user-images.githubusercontent.com/13406350/54001162-e5f71180-410f-11e9-8be5-4c3deb9ef4e8.png)

**Comment by SachaG** [comment] 2019-03-09 00:26
This is an error that people sometimes experience but we haven't been able to find the root cause yet. It can usually be fixed by deleting `node_modules`, and then reinstalling your packages again with `yarn` instead of `npm install`.

**Closed** 2019-03-09 02:08 UTC
