### ISSUE TITLE
current vision to vulcanJS

### ISSUE THREAD

**Issue by TomFreudenberg** [VulcanJS/Vulcan-Starter#169] opened 2020-04-29 01:40 UTC
Hi @SachaG 

before trying and starting to think about using VulcanJS I would like you to ask about the effort is spent on VulcanJS currently and in future.

Is this becoming "a dead project" or are you continuing pushing it forward ?

It would be great to get a simple answer before I may start a project using VulcanJS.

Currently the starter for me does not work and there are a number of old dated issues and PRs.

Thanks in any way
Tom

**Comment by eric-burel** [comment] 2020-04-29 08:48
Hi Tom,

Will answer for Sacha, I am currently taking care of issues and PR.

Short answer: the project is still active. We are preparing a migration toward NPM and Next.js, as a replacement for Meteor, that will make up the "v2" of Vulcan. The Meteor "v1" will still be maintained, for a very good reason: most of the code will be shared (schema system, graphql code generation, React components....).

You should come to the Slack and describe your project more precisely so we can tell you if the current implementation of Vulcan is suited for you, or what technologies you may want to use instead.

Regarding the broken Starter, the issue is sadly on Meteor side. Server build tend to fail when handling some packages (Material ui icons, no-ssr, but maybe some others), I can't tell why at this point. 
You should raise this issue to the Meteor community on the forum. Those kind of annoying build issues are the very reason we have been wanting to leave Meteor for a while.

Regarding old open issues, this makes sense as Vulcan is one of the oldest framework around. Some issues have been around for years simply because we lacked the correct technological answer to them (need more maturity of either React or Apollo, not emergencies, feature requests, unclear issues...). 
A good example: e2e testing. The ecosystem was just nonsensical until Cypress came out, so we left a PR open for basically 2 years because they simply were no good lib to handle e2e tests.
Current version of Vulcan is relatively stable feature wise, we did code most of the things that are actually necessary to develop an app quickly, and we fix bugs as they come.

Also we have a policy of not closing issue when they are not active, contrary to many frameworks and lib that closes issues eagerly. They have better stats but they just don't care about legitimate issues that do not receive enough attention.

**Closed** 2020-04-29 08:54 UTC

**Comment by TomFreudenberg** [comment] 2020-04-29 08:57
Hi Eric, 

Thanks a lot for your answer in details.

I came along after reading this article from Sascha (again)

https://medium.com/@sachagreif/an-open-letter-to-the-new-owners-of-meteor-353d64780b20

So yeah, leaving meteor now makes sense and is consequent. Very sad story for that "unicorn" project.

See you on Slack.

Cheers
Tom
